{
 "title": "Basic Demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Items Count Hist",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "items_h_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Items Count Only Last 5 Min",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "items_h_bucket - (items_h_bucket offset 5m)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Items Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    { "expr": "items_g" }
   ]
  },
  {
   "title": "Items Count Change Last 5Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "rate(items_g[5m]) - rate(items_g[5m] offset 5m)"
    }
   ]
  },
  {
   "title": "Standardized Mean Difference",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(rate(items_g[5m]) - rate(items_g[5m] offset 5m)) / sqrt((stddev_over_time(items_g[5m])*stddev_over_time(items_g[5m]) + stddev_over_time(items_g[5m] offset 5m)*stddev_over_time(items_g[5m] offset 5m))/2)"
    }
   ]
  },
  { "title": "Predictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Normal Stores Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "normal_class_total" }
   ]
  },
  {
   "title": "Successful Stores Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "success_class_total" }
   ]
  }
 ]
}