global:
  scrape_interval:     5s
  external_labels:
      monitor: 'ml-app'

rule_files:

scrape_configs:
  - job_name: 'app'
    dns_sd_configs:
      - names: ['app']
        port: 8000
        type: A
        refresh_interval: 3s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
