{
 "title": "Basic Demo",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Items Count Hist",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "items_h_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Items Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "targets": [
    { "expr": "items_g" }
   ]
  },
  { "title": "Predictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Normal Stores Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "normal_class_total" }
   ]
  },
  {
   "title": "Successful Stores Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "success_class_total" }
   ]
  },
  {
   "title": "Successful Stores Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "success_class_total / (success_class_total + normal_class_total)"
    }
   ]
  }
 ]
}