version: '3'
services:
  # app with metrics enabled
  app:
    build:
      context: app
    ports:
      - 8000:8000
  # the Prometheus server
  prometheus:
    image: prom/prometheus:v2.36.1
    container_name: 'prometheus'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  # Grafana for visualization
  grafana:
    image: grafana/grafana:8.5.5
    container_name: 'grafana'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
